### ISSUE TITLE
osm2pgsql should not perform analyze by itself

### ISSUE THREAD

**Issue by anayrat** [osm2pgsql-dev/osm2pgsql#2094]
Hello,

At openstreetmap france, we noticed osm2pgsql perform ``ANALYZE`` on some tables.  Unfortunately, this task cancel autovacuum :

```
2023-10-16 00:00:37.086 UTC [1643288-1]: db=osm,user=osm2pgsql,app=osm2pgsql,client=[local],xid=0 LOG:  process 1643288 still waiting for ShareUpdateExclusiveLock on relation 18197 of database 16402 after 1000.160 ms
2023-10-16 00:00:37.086 UTC [1643288-2]: db=osm,user=osm2pgsql,app=osm2pgsql,client=[local],xid=0 DETAIL:  Process holding the lock: 1640734. Wait queue: 1643288.
2023-10-16 00:00:37.086 UTC [1643288-3]: db=osm,user=osm2pgsql,app=osm2pgsql,client=[local],xid=0 STATEMENT:  ANALYZE "planet_osm_ways"
2023-10-16 00:00:37.086 UTC [1640734-1]: db=,user=,app=,client=,xid=0 ERROR:  canceling autovacuum task
2023-10-16 00:00:37.086 UTC [1640734-2]: db=,user=,app=,client=,xid=0 CONTEXT:  while vacuuming index "planet_osm_ways_nodes_bucket_idx" of relation "public.planet_osm_ways"
        automatic vacuum of table "osm.public.planet_osm_ways"
2023-10-16 00:00:37.086 UTC [1643288-4]: db=osm,user=osm2pgsql,app=osm2pgsql,client=[local],xid=0 LOG:  process 1643288 acquired ShareUpdateExclusiveLock on relation 18197 of database 16402 after 1000.476 ms
2023-10-16 00:00:37.086 UTC [1643288-5]: db=osm,user=osm2pgsql,app=osm2pgsql,client=[local],xid=0 STATEMENT:  ANALYZE "planet_osm_ways"
```

 We have an issue with a big table (`planet_osm_ways`). Postgres try to perform an autovacuum on this table, but the task is canceled by osm2pgsql. As the table is big, we can't perform autovacuum before osm2pgsql start analyze.
Thus, the table is never vacuumed and Postgres trying to vacuum it consume many I/Os.

We should rely on Postgres autovacuum, since pg 13, it is even able to start vacuum/analyze on append only table. osm2pgsql do not have to execute ANALYZE by tself.

Regards,

**Comment by joto** [comment]
I have seen the same issues in logs, too. Interestingly enough I came to the opposite conclusion: Maybe we have to do the `VACUUM` ourselves also instead of relying on the autovacuum to do its jobs whenever it feels like doing so. The problem from my experience is that working with a table that has not been analyzed can mean PostgreSQL will choose a disastrous plan and that's something we can not risk. I know that eventually PostgreSQL will probably get around to doing the ANALYZE  automatically, but "eventually" is not something I can work with.

And there is another issue behind this. Why is the vacuum even necessary? We created that table and we fill it with COPY. If I understand the docs correctly, we should be able to do a `COPY FREEZE` which means we don't need the vacuum, doesn't it? Currently we can not do this easily because of the way the code is structured (table creation and copy is run in different threads), but maybe this would be a better solution.

**Comment by joto** [comment]
> Usually, t is not the application's job to worry about how the RDBMS clean the tables.

Yeah, I know. Unfortunately our use case seems sufficiently unusual that we are constantly coming up against these kinds of problems where the database isn't magically doing the right thing.

> From what I can see, new tuples are inserted or deleted.

Only in "append" mode, i.e. when updating the data. And in that case osm2pgsql should not run `ANALYZE`. In "create" mode, `ANALYZE` is run explicitly. Are you seing those explicit `ANALYZE`s in "append" mode?

**Comment by joto** [comment]
Looking more closely at your log snippet I am seeing something strange. The autovacuum seems to be working on "planet_osm_ways_nodes_bucket_idx", but that index is only created after the `ANALYZE "planet_osm_ways"` it seems to be blocking on. So that should not happen.

What version of osm2pgsql are you running?

**Comment by anayrat** [comment]
We use version 1.4.1, I ask someone to answer other questions :) 
And yes, I see explicit ANALYZE (see logs above).

**Comment by anayrat** [comment]
Oh, I see it is an old version, and osm2pgsql's behavior has changed in 1.5.2 around analyze.

**Comment by anayrat** [comment]
Just FTR, we updated using backport (debian bulleyes). The problem is fixed. Furthermore, queries are faster. Thanks for yours answers, and sorry for the noise.

**Comment by pnorman** [comment]
PostgreSQL's autoanalyze works okay normally, but because we know what the upcoming usage of the table will be, we can do better by forcing it manually at appropriate times.

**Comment by anayrat** [comment]
Yes, but you have to keep in mind the analyze can prevent vacuum.

**Comment by pnorman** [comment]
That's fine, at no point during the import should vacuum be run. There's no need to vacuum the tables in the processing or phase 2 parts of the import, because they get rewritten in the postprocessing.

**Comment by joto** [comment]
> There's no need to vacuum the tables in the processing or phase 2 parts of the import, because they get rewritten in the postprocessing.

That's only true for the output tables, the middle tables don't get rewritten.

**Comment by pnorman** [comment]
But the middle tables are append-only during import, so there's no dead tuples.

**Comment by anayrat** [comment]
Not at all. In our case, the daemon was cancelled by analyze. Then, it was restarted, but it took a long time to vacuum a big table and before the next vacuum finish, it was again cancelled by analyze.
