### ISSUE TITLE
2.0.0 build error against GCC 14

### ISSUE THREAD

**Issue by devrimgunduz** [osm2pgsql-dev/osm2pgsql#2256]
Hi,

2.0.0 fails to build on Fedora 40 which has GCC 14. I'm unable to try this against other GCC versions today. I'll let you know when I test. Errors are attached. Can you please take a look?

Thanks! Devrim

[osm2pgsql-2.0.0-build_error_gcc_14.txt](https://github.com/user-attachments/files/17062035/osm2pgsql-2.0.0-build_error_gcc_14.txt)

**Comment by joto** [comment]
The error messages mention `fmt::v10` but the included fmt has version 11. Please post *all* information about how you have tried to compile this.

I especially like the line somewhere at the end where it says:
```
/usr/include/c++/14/bits/stl_iterator_base_funcs.h:162:7: warning: iteration 9223372036854775807 invokes undefined behavior [-Waggressive-loop-optimizations]
```

I am glad GCC is on the job making sure that the program will keep running after the end of the universe. :-)

**Comment by joto** [comment]
I tried it and GCC 14 is fine. The problem is with the fmt library. Unfortunately they change their interface slightly with every version and they don't care about backwards compatibility and don't document changes in a way that it is possible to write code in a way that it works with several versions. That's why we include a version that works with osm2pgsql. Please use that version.

If somebody wants to find out what the problem is and submit a PR, please do so.

**Comment by devrimgunduz** [comment]
Thank you! I edited RPM spec file and disabled external FMT library.
